apiVersion: v1
kind: Service
metadata:
  name: faasock-websocket-service
  namespace: faasock
spec:
  selector:
    app: faasock-websocket
  ports:
  - name: websocket
    port: 8080
    targetPort: 8080
  - name: health
    port: 3000
    targetPort: 3000
  type: LoadBalancer
